apiVersion: batch/v1
kind: CronJob
metadata:
  name: node-printer
  namespace: negmatov
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      parallelism: 2
      completions: 10
      template:
        metadata:
          labels:
            app: node-printer
        spec:
          containers:
          - name: nginx
            image: nginx
            command: ["echo", "$(hostname)"]
          restartPolicy: OnFailure

