apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-echo
  name: busybox-echo
  namespace: negmatov
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - echo "The BEST DevOPS COURSE!!!"
    image: busybox
    name: busybox-echo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

