apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-application
  namespace: negmatov
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-application
  template:
    metadata:
      labels:
        app: flask-application
    spec:
      containers:
      - name: flask-app
        image: nvrbckdown/flask-app:last-practice
        resources:
          limits:
            cpu: "150m"
            memory: "128Mi"
          requests:
            cpu: "75m"
            memory: "64Mi"
