apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-res-rolesjon
  namespace: negmatov
rules:
- apiGroups: [""]
  resources: ["nodes", "namespaces", "clusterroles"]
  verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: list-resources-role-binding
  namespace: negmatov
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: list-res-rolesjon
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io

