apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask-app
  name: final-exam
  namespace: negmatov
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - image: nvrbckdown/flask-app:final-exam
        name: flask-app
        env:
        - name: AUTHOR
          valueFrom:
            configMapKeyRef:
              name: configmaps
              key: author
        - name: POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
